FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG C.UTF-8
RUN sed -i 's@http://archive.ubuntu.com/ubuntu/@http://mirrors.aliyun.com/ubuntu/@g' /etc/apt/sources.list
RUN apt-get update && apt-get upgrade
RUN apt-get clean && apt-get update && apt-get install -y python3 python3-dev python3-pip
RUN apt-get clean && apt-get autoclean
RUN apt-get update -q && apt-get install -y wget curl nano git
RUN ln -sf /usr/bin/pip3 /usr/bin/pip && ln -sf /usr/bin/python3 /usr/bin/python
WORKDIR /root/yolov5
COPY rknn_model.py /root/yolov5/

# RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
# 上述过程是构建Python环境，用于创建python环境
# apt-get 安装 wget curl nano
# ENTRYPOINT [ "/root/directory/docker_init.sh" ] # 执行shell脚本
